import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
export function TransacaoTable({ transacoes, categorias, onEdit, onDelete }) {
    const getCategoriaName = (id) => {
        return categorias.find((c) => c.id === id)?.nome || 'Desconhecida';
    };
    return (_jsxs("div", { className: "bg-white rounded-lg shadow overflow-hidden", children: [_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 border-b", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700", children: "Data" }), _jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700", children: "Categoria" }), _jsx("th", { className: "px-4 py-3 text-left text-sm font-semibold text-gray-700", children: "Descri\u00E7\u00E3o" }), _jsx("th", { className: "px-4 py-3 text-right text-sm font-semibold text-gray-700", children: "Valor" }), _jsx("th", { className: "px-4 py-3 text-center text-sm font-semibold text-gray-700", children: "Tipo" }), _jsx("th", { className: "px-4 py-3 text-center text-sm font-semibold text-gray-700", children: "M\u00E9todo" }), _jsx("th", { className: "px-4 py-3 text-center text-sm font-semibold text-gray-700", children: "A\u00E7\u00F5es" })] }) }), _jsx("tbody", { className: "divide-y", children: transacoes.map((tx) => (_jsxs("tr", { className: "hover:bg-gray-50 transition", children: [_jsx("td", { className: "px-4 py-3 text-sm", children: new Date(tx.dataTransacao).toLocaleDateString('pt-BR') }), _jsx("td", { className: "px-4 py-3 text-sm", children: _jsx("span", { className: "px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs font-medium", children: getCategoriaName(tx.categoriaId) }) }), _jsxs("td", { className: "px-4 py-3 text-sm text-gray-700", children: [tx.descricao, tx.notas && (_jsx("div", { className: "text-xs text-gray-500 mt-1", children: tx.notas }))] }), _jsx("td", { className: "px-4 py-3 text-sm text-right font-medium", children: _jsxs("span", { className: tx.tipo === 'receita' ? 'text-green-600' : 'text-red-600', children: [tx.tipo === 'receita' ? '+' : '-', " R$ ", tx.valor.toLocaleString('pt-BR', { minimumFractionDigits: 2 })] }) }), _jsx("td", { className: "px-4 py-3 text-sm text-center", children: _jsx("span", { className: `px-2 py-1 rounded text-xs font-medium ${tx.tipo === 'receita'
                                                ? 'bg-green-100 text-green-800'
                                                : 'bg-red-100 text-red-800'}`, children: tx.tipo === 'receita' ? 'Receita' : 'Despesa' }) }), _jsx("td", { className: "px-4 py-3 text-sm text-center text-gray-600", children: _jsx("span", { className: "text-xs", children: tx.metodoPagamento === 'cartao'
                                                ? '💳'
                                                : tx.metodoPagamento === 'dinheiro'
                                                    ? '💵'
                                                    : tx.metodoPagamento === 'transferencia'
                                                        ? '📱'
                                                        : '...' }) }), _jsx("td", { className: "px-4 py-3 text-sm text-center", children: _jsxs("div", { className: "flex gap-2 justify-center", children: [_jsx("button", { onClick: () => onEdit(tx), className: "p-1 hover:bg-blue-100 text-blue-600 rounded transition", title: "Editar", children: "\u270F\uFE0F" }), _jsx("button", { onClick: () => onDelete(tx.id), className: "p-1 hover:bg-red-100 text-red-600 rounded transition", title: "Deletar", children: "\uD83D\uDDD1\uFE0F" })] }) })] }, tx.id))) })] }) }), transacoes.length === 0 && (_jsx("div", { className: "text-center py-8 text-gray-600", children: "Nenhuma transa\u00E7\u00E3o para exibir" }))] }));
}
